const defaults = {
    strings: [
        'These are the default values...',
        'You know what you should do?',
        'Use your own!',
        'Have a great day!',
    ],
    stringsElement: null,
    typeSpeed: 0,
    startDelay: 0,
    backSpeed: 0,
    smartBackspace: true,
    shuffle: false,
    backDelay: 700,
    fadeOut: false,
    fadeOutClass: 'typed-fade-out',
    fadeOutDelay: 500,
    loop: false,
    loopCount: Infinity,
    showCursor: true,
    cursorChar: '|',
    autoInsertCss: true,
    attr: null,
    bindInputFocusEvents: false,
    contentType: 'html',
    onBegin: (self) => { },
    onComplete: (self) => { },
    preStringTyped: (arrayPos, self) => { },
    onStringTyped: (arrayPos, self) => { },
    onLastStringBackspaced: (self) => { },
    onTypingPaused: (arrayPos, self) => { },
    onTypingResumed: (arrayPos, self) => { },
    onReset: (self) => { },
    onStop: (arrayPos, self) => { },
    onStart: (arrayPos, self) => { },
    onDestroy: (self) => { },
};
export default defaults;
